const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const api = {};
vm.createContext(api);
vm.runInContext(fs.readFileSync(path.join(__dirname, '../Suggestions.js'), 'utf8'), api);
const client = (id, title, app = 'foot', focus = 0) => ({workspace: {id}, title, class: app, focusHistoryID: focus});
assert.equal(api.fromClients([client(3, '✳ Network Pulse plugin')])['3'], 'Network Pulse plugin');
assert.equal(api.fromClients([client(2, '▶ Song | cliamp')])['2'], 'Music');
assert.equal(api.fromClients([client(1, 'Omarchy docs - Brave', 'brave-browser')])['1'], 'Omarchy docs');
assert.equal(api.fromClients([client(4, '⠦ pi')])['4'], 'Pi');
assert.equal(api.fromClients([client(1, 'bash'), client(1, 'Project plan', 'foot', 5)])['1'], 'Project plan');
assert.equal(api.fromClients([client(1, 'Older', 'foot', 5), client(1, 'Current', 'foot', 0)])['1'], 'Current');
assert.equal(api.label({'1': 'My name'}, {'1': 'Automatic'}, 1), 'My name');
assert.equal(api.label({}, {'1': 'Automatic'}, 1), 'Automatic');
assert.equal(Object.keys(api.fromClients([client(-99, 'Scratchpad')])).length, 0);
const before = api.fromClients([client(7, 'Project Seven')]);
const after = api.fromClients([client(2, 'Project Seven')]);
assert.equal(before['7'], after['2']);
assert.equal(after['7'], undefined, 'no stale suggestion after Plonk renumbering');
assert.equal(Object.keys(api.fromClients([])).length, 0, 'closed windows clear suggestions');
console.log('Suggestion tests passed');
